// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfHiPadJ5GeB25oRESxvHMuqs9XoUsArY',
    appId: '1:370172359890:web:ef40ddf5bfa7b6c019290b',
    messagingSenderId: '370172359890',
    projectId: 'global-connect-87260',
    authDomain: 'global-connect-87260.firebaseapp.com',
    storageBucket: 'global-connect-87260.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfeeGhwuUwdfoD5hpo6lfPLHh-Hq34574',
    appId: '1:370172359890:android:6aa50a65f121d54219290b',
    messagingSenderId: '370172359890',
    projectId: 'global-connect-87260',
    storageBucket: 'global-connect-87260.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALIkpLmdafbMUzMzhsrb2Suj4aIGJx2fw',
    appId: '1:370172359890:ios:3826e8486ffdb05119290b',
    messagingSenderId: '370172359890',
    projectId: 'global-connect-87260',
    storageBucket: 'global-connect-87260.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALIkpLmdafbMUzMzhsrb2Suj4aIGJx2fw',
    appId: '1:370172359890:ios:3826e8486ffdb05119290b',
    messagingSenderId: '370172359890',
    projectId: 'global-connect-87260',
    storageBucket: 'global-connect-87260.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfHiPadJ5GeB25oRESxvHMuqs9XoUsArY',
    appId: '1:370172359890:web:842c227727b732e219290b',
    messagingSenderId: '370172359890',
    projectId: 'global-connect-87260',
    authDomain: 'global-connect-87260.firebaseapp.com',
    storageBucket: 'global-connect-87260.appspot.com',
  );
}
